app/main/routes.py
# coding: latin-1
###############################################################################
# Copyright (c) 2023 European Commission
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

import os
from flask import (Blueprint, render_template)
from app_config.config import ConfService as cfgserv

base = Blueprint("index", __name__, url_prefix="/")
base.template_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'template/')

@base.route('/', methods=['GET'])
def index():
    return render_template('index.html', redirect_url= cfgserv.service_url)

app/routes.py
# coding: latin-1
###############################################################################
# Copyright (c) 2023 European Commission
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

import os, base64, base64, mimetypes
from flask import (
    Blueprint,
    render_template,
    request,
    redirect, 
    url_for,
    session,
    send_from_directory,
    current_app as app
)

from app_config.config import ConfService as cfgserv
import app.model.qtsp_client as qc, app.model.sca_client as sc, app.model.rp_client as rc, app.model.documents_manage as dm
from cryptography.x509.oid import _SIG_OIDS_TO_HASH 
from cryptography.hazmat._oid import ObjectIdentifier

tester = Blueprint("tester", __name__, url_prefix="/tester")
tester.template_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'template/')

env_var = os.getenv('ENV_TYPE', 'demo')

DIGEST_OIDS = {
    "md5": "1.2.840.113549.2.5",
    "sha1": "1.3.14.3.2.26",
    "sha224": "2.16.840.1.101.3.4.2.4",
    "sha256": "2.16.840.1.101.3.4.2.1",
    "sha384": "2.16.840.1.101.3.4.2.2",
    "sha512": "2.16.840.1.101.3.4.2.3",
    "sha3_224": "2.16.840.1.101.3.4.2.7",
    "sha3_256": "2.16.840.1.101.3.4.2.8",
    "sha3_384": "2.16.840.1.101.3.4.2.9",
    "sha3_512": "2.16.840.1.101.3.4.2.10",
}

global code_verifier, documentLocations, response_uri

@tester.route('/', methods=['GET'])
def main():
    return render_template('main.html', redirect_url= cfgserv.service_url)

@tester.route("/relying_party_service", methods=["GET"])
def getRelyingPartyService():
    request_uri = request.args.get("request_uri")
    client_id = request.args.get("client_id")
    
    response_uri_l, _, hash_algorithm_oid, document_locations = rc.get_request_object_from_rp(request_uri, client_id)
    
    update_session_values("response_uri", response_uri_l)
    update_session_values("hash_algorithm_oid", hash_algorithm_oid)
    update_session_values("documentLocations", document_locations)
    global documentLocations
    documentLocations = document_locations

    global response_uri
    response_uri = response_uri_l
    
    return redirect(url_for("tester.service_authentication"))

# starts the authentication process through the /oauth2/authorize and receives the link to the wallet
@tester.route('/auth/service', methods=['GET'])
def service_authentication():
    app.logger.info("Starting the authentication process.")
    
    try:
       code_verifier_local, location = qc.oauth2_authorize_service_request()
    except Exception as e:
        app.logger.error("Error: "+str(e))
        return str, 400

    update_session_values(variable_name="code_verifier", variable_value=code_verifier_local)
    global code_verifier
    code_verifier = code_verifier_local

    app.logger.info("Displaying the authentication page.")

    return render_template('auth.html', redirect_url=cfgserv.service_url, env_var=env_var, location=location)

@tester.route("/auth/service/success", methods=["GET", "POST"])
def service_authentication_successful():
    return render_template('auth_success_page.html', redirect_url= cfgserv.service_url, access_token_value=session.get("service_access_token"), env_var=env_var)

# endpoint where the qtsp will be redirected to after authentication
@tester.route("/oauth/login/code", methods=["GET", "POST"])
def oauth_login_code():
    code = request.args.get("code")
    state = request.args.get("state")
    error = request.args.get("error")
    error_description=request.args.get("error_description")
    
    app.logger.info("Received request with code: %s and state: %s", code, state)
    
    if error:
        app.logger.error("Received Error %s: %s", error, error_description)
        return render_template('500.html', error= error+": "+error_description)
    
    # code_verifier = session.get("code_verifier")
    if code_verifier is None:
        app.logger.error("Session key 'code_verifier' is missing.")
        return render_template('500.html', error="Session expired or invalid request.")
    
    if code is None:
        app.logger.error("No authorization code received.")
        return render_template('500.html', error="Missing authorization code.")
    
    try:
        app.logger.info("Requesting token with code: "+code+" and code_verifier: "+code_verifier)
        scope, access_token = qc.oauth2_token_request(code, code_verifier) # trades the code for the access token
    except Exception as e:
        app.logger.error("Error during OAuth token request: %s", str(e), exc_info=True)
        return render_template('500.html', error="OAuth token request failed.")
              
    if(scope == "service"):
        remove_session_values(variable_name="code_verifier")    
        update_session_values(variable_name="service_access_token", variable_value=access_token)
        return redirect(url_for("tester.service_authentication_successful"))
    elif(scope == "credential"):
        remove_session_values(variable_name="code_verifier")
        update_session_values(variable_name="credential_access_token", variable_value=access_token)
        return redirect(url_for("tester.upload_document"))

@tester.route("/credentials/list", methods=["GET"])
def list_credentials():
    list_credentials_ids = qc.csc_v2_credentials_list(session.get("service_access_token"))
    return render_template('credential.html', redirect_url=cfgserv.service_url, credentials=list_credentials_ids)

@tester.route("/credentials/select", methods=["POST"])
def select_credential():
    credential_id = request.get_json().get("credentialID")
    app.logger.info("Selected credential: "+credential_id)
    update_session_values(variable_name="credentialID", variable_value=credential_id)
    
    app.logger.info("Requesting information about the selected credential.")
    certificates, key_algos = qc.csc_v2_credentials_info(session.get("service_access_token"), credential_id)
    
    update_session_values(variable_name="end_entity_certificate", variable_value=certificates[0])
    update_session_values(variable_name="certificate_chain", variable_value=certificates[1])
    update_session_values(variable_name="key_algos", variable_value=key_algos)
        
    return "success"

@tester.route('/document/select', methods=['GET'])
def select_document():
    key_algos = session.get("key_algos")
    hash_algos = []
    for algo in key_algos:
        hash_algo = _SIG_OIDS_TO_HASH.get(ObjectIdentifier(algo))
        if hash_algo is not None:
            hash_algos.append({"name":hash_algo.name.upper(), "oid":DIGEST_OIDS.get(hash_algo.name.lower())})
    
    # documentLocations = session.get("documentLocations")
    if documentLocations is not None:
        for loc in documentLocations:
            document, filename = rc.get_document_from_uri(loc['uri'])
            app.logger.info("Document received from the URI.")
            
            saved_file_path, saved_filename  = dm.save_document_with_name(document, filename)
            update_session_values(variable_name="filepath", variable_value=saved_file_path)
            update_session_values(variable_name="filename", variable_value=saved_filename)
            
            app.logger.info("Document saved at "+saved_file_path)
                        
            url = cfgserv.service_url+"/document/"+saved_filename
            app.logger.info("Generated an URL to retrieve the document.")
        return render_template('pdf.html', redirect_url= cfgserv.service_url, digest_algorithms=hash_algos, mode="view", file_url=url)
    
    else:
        return render_template('pdf.html', redirect_url= cfgserv.service_url, digest_algorithms=hash_algos, mode = "upload")

@tester.route('/document/<path:filename>', methods=["GET"])
def serve_document(filename):
    return send_from_directory("documents", filename)

@tester.route("/auth/credential", methods=["POST"])
def credential_authorization():
    #documentLocations = session.get("documentLocations")
    
    if documentLocations is None:
        document = request.files['upload']
        file_path, filename = dm.save_document(document)
        update_session_values(variable_name="filepath", variable_value=file_path)
        update_session_values(variable_name="filename", variable_value=filename)
        base64_pdf= base64.b64encode(document.read()).decode("utf-8")
        document.stream.seek(0)
    else:
        file_path = session.get("filepath")
        filename = session.get("filename")
        base64_pdf = dm.get_base64_document(file_path)
        
    form_local= request.form
    container=form_local["container"]
    update_session_values(variable_name="container", variable_value=container)
    signature_format= form_local["signature_format"]
    update_session_values(variable_name="signature_format", variable_value=signature_format)
    signed_envelope_property= form_local["packaging"]
    update_session_values(variable_name="signed_envelope_property", variable_value=signed_envelope_property)
    conformance_level= form_local["level"]
    update_session_values(variable_name="conformance_level", variable_value=conformance_level)
    hash_algorithm_oid= form_local["algorithm"]
    update_session_values(variable_name="hash_algorithm_oid", variable_value=hash_algorithm_oid)

    hashes, signature_date = sc.calculate_hash_request(
            base64_pdf,
            filename,
            signature_format,
            conformance_level,

app/templates/auth.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <h1>QTSP Authentication</h1>
      <div class="genericErrors" id="genericErrorsDesc"></div>

      <a
        class="btn custom-btn"
        id="fetchButton"
        onclick="serviceAuthentication()"
        >Authenticate</a
      >

      <div id="container-redirect-wallet" class="btn custom-btn">
        <a id="link_to_wallet" href="{{ location }}">Go to EUDI Wallet</a>
      </div>

      {% if env_var == "dev" %}
      <div id="dev-div" style="width: 100%; margin-top: 20px">
        <p style="font-weight: bold">Link to EUDI Wallet:</p>
        <p id="result">{{ location }}</p>
        <p id="description" style="font-weight: bold">
          After authorization the wallet will redirect to a link. Introduce link
          redirect to in the input box below.
        </p>
        <input
          type="text"
          id="authLink"
          placeholder="Enter your response here"
        />
        <button
          class="btn sign-custom-btn"
          style="margin-top: 0px"
          id="submitButton"
          onclick="submitButton()"
        >
          Submit Text
        </button>
        <a
          id="link-to-continue"
          class="btn sign-custom-btn"
          style="margin-top: 0px"
          >Continue</a
        >
      </div>
      {% endif %}
    </div>
  </div>
</div>
<script>
  document.getElementById("container-redirect-wallet").hidden = true;
  if ("{{env_var}}" === "dev") {
    document.getElementById("dev-div").hidden = true;
    document.getElementById("link-to-continue").hidden = true;
  }

  async function serviceAuthentication() {
    document.getElementById("container-redirect-wallet").hidden = false;
    if ("{{env_var}}" === "dev") {
      document.getElementById("dev-div").hidden = false;
    }
  }

  async function submitButton() {
    const userInput = document.getElementById("authLink").value;
    document.getElementById("link-to-continue").href = userInput;
    document.getElementById("link-to-continue").hidden = false;
  }
</script>
{% endblock %}

app/templates/auth_success.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <h1>QTSP Authentication</h1>
      <div class="genericErrors" id="genericErrorsDesc"></div>

      <h2>Successful Authentication</h2>

      {% if env_var == "dev" %}
      <div style="width: 100%; margin-top: 20px">
        <label style="font-weight: bold">Access Token:</label>
        <p id="accesstoken" style="word-wrap: break-word">
          {{access_token_value}}
        </p>
      </div>
      {% endif %}

      <a class="btn custom-btn" href="{{redirect_url}}/credentials_list"
        >Continue to CredentialsPage</a
      >
    </div>
  </div>
</div>
{% endblock %}

app/templates/auth_success_page.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <h1>QTSP Authentication</h1>
      <div class="genericErrors" id="genericErrorsDesc"></div>

      <h2>Successful Authentication</h2>

      {% if env_var == "dev" %}
      <div style="width: 100%; margin-top: 20px">
        <label style="font-weight: bold">Access Token:</label>
        <p id="accesstoken" style="word-wrap: break-word">
          {{access_token_value}}
        </p>
      </div>
      {% endif %}

      <a class="btn custom-btn" href="{{ url_for('tester.list_credentials') }}"
        >Continue to CredentialsPage</a
      >
    </div>
  </div>
</div>
{% endblock %}

app/templates/credential.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <h1>Available Credentials</h1>
      <div class="genericErrors" id="genericErrorsDesc"></div>
      <div id="response"></div>
    </div>
  </div>
</div>
<script>
  const credential_list = {{ credentials | tojson }};
  console.log(credential_list);

  window.onload = function () {
    const container = document.getElementById("response");

    credential_list.forEach((credential) => {
      const credentialItem = document.createElement("div");
      credentialItem.textContent = credential;
      credentialItem.style.cursor = "pointer";
      credentialItem.style.padding = "5px";
      credentialItem.style.margin = "5px 0";
      credentialItem.style.border = "1px solid #ccc";
      credentialItem.style.borderRadius = "4px";
      credentialItem.style.backgroundColor = "#f9f9f9";

      credentialItem.addEventListener("click", function () {
        fetch("{{ url_for('tester.select_credential') }}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ credentialID: credential }),
        })
          .then((response) => {
            window.location.href = "{{ url_for('tester.select_document') }}";
          })
          .catch((error) => {
            console.error("Error:", error);
          });
      });

      container.appendChild(credentialItem);
    });
  };
</script>
{% endblock %}

app/templates/credential_authorization.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <h1>Credential Authorization</h1>
      <div class="genericErrors" id="genericErrorsDesc"></div>
      <h3>Authorize credential usage to sign document</h3>

      <div id="container-redirect-wallet" class="btn custom-btn">
        <a id="link_to_wallet" href="{{location}}">Go to EUDI Wallet</a>
      </div>

      {% if env_var == "dev" %}
      <div id="temp" style="width: 100%; margin-top: 20px">
        <p style="font-weight: bold">Link to EUDI Wallet:</p>
        <p id="result">{{location}}</p>
        <p id="description" style="font-weight: bold">
          After authorization the wallet will redirect to a link. Introduce link
          redirect to in the input box below.
        </p>
        <input
          type="text"
          id="authLink"
          placeholder="Enter your response here"
        />
        <button
          class="btn sign-custom-btn"
          style="margin-top: 0px"
          id="submitButton"
          onclick="submitButton()"
        >
          Submit Text
        </button>
        <a
          id="link_to_continue"
          class="btn sign-custom-btn"
          style="margin-top: 0px"
          >Continue</a
        >
      </div>
      {% endif %}
    </div>
  </div>
</div>

<script>
  if ("{{env_var}}" === "dev") {
    document.getElementById("link_to_continue").hidden = true;
  }

  async function submitButton() {
    const userInput = document.getElementById("authLink").value;
    document.getElementById("link_to_continue").href = userInput;
    document.getElementById("link_to_continue").hidden = false;
  }
</script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1>rQES (Wallet Centric)</h1>
    <div id="content" class="content-wrap1 content-center col-md-11 col-sm-11">
      <div class="genericErrors" id="genericErrorsDesc"></div>
      <p>
        Welcome to the remote Qualified Eletronic Signature component
        wallet-centric backend server.
      </p>
      <p>
        A Web GUI supporting the same-flow device for tests is available at:
        <a href="{{redirect_url}}"
          >https://walletcentric.signer.eudiw.dev/tester</a
        >
      </p>

      <p>
        In this domain, it is made available the SCA Server and the QTSP Server
        composed by an Authorization Server and Resourse Server.
      </p>

      <p>SCA Server Endpoints:</p>
      <ul>
        <li>/credential/authorize</li>
        <li>/signatures/signDoc</li>
        <li>/credential/oauth/login/code</li>
      </ul>

      <p>QTSP Server Endpoints:</p>
      <ul>
        <li>
          Authorization Server
          <ul>
            <li>/oauth2/authorize</li>
            <li>/oauth2/token</li>
            <li>/oid4vp/callback</li>
          </ul>
        </li>
        <li>
          Resource server
          <ul>
            <li>/csc/v2/info</li>
            <li>/csc/v2/signatures/signHash</li>
            <li>/csc/v2/credentials/list</li>
            <li>/csc/v2/credentials/info</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

app/templates/main.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <div class="main-page-box">
        <h3>EUDI Wallet</h3>
        <h1>Welcome to the rQES Wallet Tester</h1>
        <p
          style="
            font-size: 15px;
            font-family: 'Gill Sans', serif;
            margin-bottom: 30px;
          "
        >
          This is a web application that allows users to test the
          functionalities of the EUDI Wallet rQES.
        </p>
        <div class="genericErrors" id="genericErrorsDesc"></div>
        <form
          action="{{ url_for('tester.service_authentication') }}"
          method="GET"
        >
          <!-- Submit button -->
          <button class="btn custom-btn" type="submit">Start</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/pdf.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <div class="genericErrors" id="genericErrorsDesc"></div>

      <h1>Sign Document</h1>

      <form
        method="post"
        action="{{ url_for('tester.credential_authorization') }}"
        accept-charset="UTF-8"
        enctype="multipart/form-data"
        autocapitalize="off"
        spellcheck="false"
        style="padding-top: 10px"
      >
        {% if mode == "upload" %}
        <h2>Step 1: Select Document</h2>
        <div
          class="form-check col-md-12 d-flex justify-content-center align-items-center"
        >
          <label
            class="btn sign-custom-btn"
            style="width: fit-content"
            for="filename"
          >
            Choose Document
          </label>
          <input
            type="file"
            name="upload"
            id="filename"
            style="display: none"
          />
        </div>

        <iframe
          id="viewer"
          frameborder="0"
          scrolling="auto"
          height="500px"
          width="100%"
          type="application/pdf"
          style="border: 1px solid #ccc; margin-top: 10px"
        ></iframe>
        {% elif mode == "view" %}
        <h2>Step 1: Confirm Document Received</h2>
        <iframe
          id="viewer"
          frameborder="0"
          scrolling="auto"
          height="500px"
          width="100%"
          src="{{ file_url }}"
          type="application/pdf"
          style="border: 1px solid #ccc; margin-top: 10px"
        ></iframe>
        {% endif %}

        <h2 style="margin-top: 10px">Step 2: Select Signature Options</h2>

        <div class="col-md-12 signature-options">
          <h3>Container</h3>
          <div class="form-group">
            <label class="radio-inline">
              <input type="radio" id="No" name="container" value="No" checked />
              No
            </label>
            <label class="radio-inline">
              <input type="radio" id="ASiC-S" name="container" value="ASiC-S" />
              ASiC-S
            </label>
            <label class="radio-inline">
              <input type="radio" id="ASiC-E" name="container" value="ASiC-E" />
              ASiC-E
            </label>
          </div>
        </div>
        <div class="col-md-12 signature-options">
          <h3>Signature format</h3>
          <div class="form-group">
            <label class="radio-inline">
              <input
                type="radio"
                id="XAdES"
                name="signature_format"
                value="X"
                required
              />
              XAdES
            </label>
            <label class="radio-inline">
              <input
                type="radio"
                id="CAdES"
                name="signature_format"
                value="C"
              />
              CAdES
            </label>
            <label class="radio-inline">
              <input
                type="radio"
                id="PAdES"
                name="signature_format"
                value="P"
              />
              PAdES
            </label>
            <label class="radio-inline">
              <input
                type="radio"
                id="JAdES"
                name="signature_format"
                value="J"
              />
              JAdES
            </label>
          </div>
        </div>
        <div class="col-md-12 signature-options">
          <h3>Packaging</h3>
          <div class="form-group">
            <label class="radio-inline">
              <input
                type="radio"
                id="enveloped"
                name="packaging"
                value="ENVELOPED"
                disabled
                required
              />
              Enveloped
            </label>
            <label class="radio-inline">
              <input
                type="radio"
                id="enveloping"
                name="packaging"
                value="ENVELOPING"
                disabled
              />
              Enveloping
            </label>
            <label class="radio-inline">
              <input
                type="radio"
                id="detached"
                name="packaging"
                value="DETACHED"
                disabled
              />
              Detached
            </label>
            <label class="radio-inline">
              <input
                type="radio"
                id="internally"
                name="packaging"
                value="INTERNALLY_DETACHED"
                disabled
              />
              Internally detached
            </label>
          </div>
        </div>
        <div class="col-md-12 signature-options">
          <h3>Level</h3>
          <select id="select" class="form-control" name="level"></select>
        </div>
        <div class="col-md-12 signature-options">
          <h3>Digest algorithm</h3>
          <div class="form-group">
            {% for algorithm in digest_algorithms %}
            <label class="radio-inline">
              <input
                type="radio"
                id="inlineCheckbox1"
                name="algorithm"
                value="{{ algorithm.oid }}"
                {%
                if
                loop.first
                %}checked{%
                endif
                %}
              />
              {{ algorithm.name }}
            </label>
            {% endfor %}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Continue</button>
      </form>
    </div>
  </div>
</div>

<script type="text/javascript">
  let XAdES = document.getElementById("XAdES");
  let CAdES = document.getElementById("CAdES");
  let PAdES = document.getElementById("PAdES");
  let JAdES = document.getElementById("JAdES");

  let enveloped = document.getElementById("enveloped");
  let enveloping = document.getElementById("enveloping");
  let detached = document.getElementById("detached");
  let internally_detached = document.getElementById("internally");
  let select = document.getElementById("select");

  function populate_select(options) {
    options.forEach((option) => {
      const newOption = document.createElement("option");
      newOption.value = option.value;
      newOption.textContent = option.text;
      select.appendChild(newOption);
    });
  }

  $("input[type=radio][name=container]").change(function () {
    var radio = document.getElementsByName("signature_format");

    for (var i = 0; i < radio.length; i++) {
      radio[i].checked = false;
    }

    var radio2 = document.getElementsByName("packaging");

    for (var i = 0; i < radio2.length; i++) {
      radio2[i].checked = false;
    }

    select.innerHTML = "";

    if (this.value == "No") {
      XAdES.disabled = false;
      CAdES.disabled = false;
      PAdES.disabled = false;
      JAdES.disabled = false;
    } else if (this.value == "ASiC-S" || this.value == "ASiC-S") {
      XAdES.disabled = false;
      CAdES.disabled = false;
      PAdES.disabled = true;
      JAdES.disabled = true;
    }
  });

  $("input[type=radio][name=signature_format]").change(function () {
    var radio = document.getElementsByName("packaging");

    for (var i = 0; i < radio.length; i++) {
      radio[i].checked = false;
    }

    select.innerHTML = "";

    if (this.value == "X") {
      enveloped.disabled = false;
      enveloping.disabled = false;
      detached.disabled = false;
      internally_detached.disabled = false;

      var options = [
        { value: "Ades-B-B", text: "XAdES-BASELINE-B" },
        { value: "Ades-B-T", text: "XAdES-BASELINE-T" },
        { value: "Ades-B-LT", text: "XAdES-BASELINE-LT" },
        { value: "Ades-B-LTA", text: "XAdES-BASELINE-LTA" },
      ];

      populate_select(options);
    } else if (this.value == "C") {
      enveloped.disabled = true;
      enveloping.disabled = false;
      detached.disabled = false;
      internally_detached.disabled = true;

      var options = [
        { value: "Ades-B-B", text: "CAdES-BASELINE-B" },
        { value: "Ades-B-T", text: "CAdES-BASELINE-T" },
        { value: "Ades-B-LT", text: "CAdES-BASELINE-LT" },
        { value: "Ades-B-LTA", text: "CAdES-BASELINE-LTA" },
      ];

      populate_select(options);
    } else if (this.value == "P") {
      enveloped.disabled = false;
      enveloping.disabled = true;
      detached.disabled = true;
      internally_detached.disabled = true;

      var options = [
        { value: "Ades-B-B", text: "PAdES-BASELINE-B" },
        { value: "Ades-B-T", text: "PAdES-BASELINE-T" },
        { value: "Ades-B-LT", text: "PAdES-BASELINE-LT" },
        { value: "Ades-B-LTA", text: "PAdES-BASELINE-LTA" },
      ];

      populate_select(options);
    } else if (this.value == "J") {
      enveloped.disabled = true;
      enveloping.disabled = false;
      detached.disabled = false;
      internally_detached.disabled = true;

      var options = [
        { value: "Ades-B-B", text: "JAdES-BASELINE-B" },
        { value: "Ades-B-T", text: "JAdES-BASELINE-T" },
        { value: "Ades-B-LT", text: "JAdES-BASELINE-LT" },
        { value: "Ades-B-LTA", text: "JAdES-BASELINE-LTA" },
      ];

      populate_select(options);
    }

    var value_container = document.querySelector(
      'input[name="container"]:checked'
    );
    if (
      value_container.value == "ASiC-S" ||
      value_container.value == "ASiC-E"
    ) {
      enveloped.disabled = true;
      enveloping.disabled = true;
      detached.disabled = false;
      internally_detached.disabled = true;
    }
  });

  document.getElementById("filename").addEventListener("change", (event) => {
    let input = event.target;
    let path = input.value;
    let file = input.files[0];
    var fileURL = URL.createObjectURL(file);
    document.getElementById("viewer").src = fileURL;
    document.getElementById("btncheck").disabled = false;
  });
</script>
{% endblock %}

app/templates/sign_document_success.html
{% extends 'base.html' %} {% block content %}
<div class="row" style="height: 100%">
  <div class="col-lg-12" style="height: 100%">
    <div id="content" class="content-box col-md-11">
      <h1>Document Signed</h1>

      <div class="genericErrors" id="genericErrorsDesc"></div>

      <p>The document was signed and sent to the Relying Party Web Portal.</p>
    </div>
  </div>
</div>
{% endblock %}